#!/usr/bin/ruby
#
# This file is part of CPEE-INSTANTIATION.
#
# CPEE-INSTANTIATION is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-INSTANTIATION is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# CPEE-INSTANTIATION (file LICENSE in the main directory).  If not, see
# <http://www.gnu.org/licenses/>.

require 'rubygems'
require 'cpee-instantiation/instantiation'

options = {
  :host => 'localhost',
  :port => 9296,
  :secure => false
}

Riddl::Server.new(CPEE::Instantiation::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:cpee] ||= 'http://localhost:8298/'

  use CPEE::Instantiation::implementation(@riddl_opts)
end.loop!
