#!/usr/bin/ruby
curpath = __dir__
require 'rubygems'
require 'optparse'
require 'fileutils'
require 'xml/smart'

def wrap(s, width=78, indent=18)
	lines = []
	line, s = s[0..indent-2], s[indent..-1]
  s.split(/\n/).each do |ss|
    ss.split(/[ \t]+/).each do |word|
      if line.size + word.size >= width
        lines << line
        line = (" " * (indent)) + word
      else
        line << " " << word
      end
    end
    lines << line if line
    line = (" " * (indent-1))
  end
	return lines.join "\n"
end

ARGV.options { |opt|
  opt.summary_indent = ' ' * 2
  opt.summary_width = 15
  opt.banner = "Usage:\n#{opt.summary_indent}#{File.basename($0)} [DIR]\n"
  opt.on("Options:")
  opt.on("--help", "-h", "This text") { puts opt; exit }
	opt.on("")
  opt.on(wrap("[DIR]        scaffolds a sample instantiation service. Post a testset to a model to keep going in one operation."))
  opt.parse!
}
if (ARGV.length != 1)
  puts ARGV.options
  exit
else
  p1 = ARGV[0]
end

if !File.exist?(p1)
  FileUtils.cp_r("#{curpath}/../server/",p1)
else
  puts 'Directory already exists.'
end
